name: Worklist-CFA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: g++ -O3 compare_stores.cpp -o compare_stores
    - name: Build
      run: make
    - name: Run tests
      run: make check
    - name: Cleanup
      run: |
        make clean
        rm -f compare-stores
